### ISSUE TITLE
Please update PyQT version to >= 5.15.5

### ISSUE THREAD

**Issue by maathieu** [argosopentech/argos-translate-gui#8]
Hi, PyQT5 version5.15.4 has no wheel for Python 3.10 which is the default install in Windows 10. When trying to install argos-translate-gui the installation will then fail with this error, as pip will try to compile QT from source:

```
C:\Users\Somebody>pip install argostranslategui
Collecting argostranslategui
  Using cached argostranslategui-1.6.3-py3-none-any.whl (6.7 kB)
Requirement already satisfied: argostranslate in c:\users\Somebody\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from argostranslategui) (1.8.0)
Collecting PyQt5==5.15.4
  Using cached PyQt5-5.15.4.tar.gz (3.3 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [22 lines of output]
      Traceback (most recent call last):
        File "C:\Users\Somebody\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\Somebody\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\Somebody\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 152, in prepare_metadata_for_build_wheel
          whl_basename = backend.build_wheel(metadata_directory, config_settings)
        File "C:\Users\Somebody\AppData\Local\Temp\pip-build-env-e2m4s112\overlay\Lib\site-packages\sipbuild\api.py", line 46, in build_wheel
          project = AbstractProject.bootstrap('wheel',
        File "C:\Users\Somebody\AppData\Local\Temp\pip-build-env-e2m4s112\overlay\Lib\site-packages\sipbuild\abstract_project.py", line 87, in bootstrap
          project.setup(pyproject, tool, tool_description)
        File "C:\Users\Somebody\AppData\Local\Temp\pip-build-env-e2m4s112\overlay\Lib\site-packages\sipbuild\project.py", line 585, in setup
          self.apply_user_defaults(tool)
        File "C:\Users\Somebody\AppData\Local\Temp\pip-install-obyn7fgf\pyqt5_137ee3c0c5534bb3aae4385f45cba038\project.py", line 63, in apply_user_defaults
          super().apply_user_defaults(tool)
        File "C:\Users\Somebody\AppData\Local\Temp\pip-build-env-e2m4s112\overlay\Lib\site-packages\pyqtbuild\project.py", line 70, in apply_user_defaults
          super().apply_user_defaults(tool)
        File "C:\Users\Somebody\AppData\Local\Temp\pip-build-env-e2m4s112\overlay\Lib\site-packages\sipbuild\project.py", line 236, in apply_user_defaults
          self.builder.apply_user_defaults(tool)
        File "C:\Users\Somebody\AppData\Local\Temp\pip-build-env-e2m4s112\overlay\Lib\site-packages\pyqtbuild\builder.py", line 69, in apply_user_defaults
          raise PyProjectOptionException('qmake',
      sipbuild.pyproject.PyProjectOptionException
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

Can you update the dependencies to use 5.15.5, which has a Python 3.10 wheel?

**Comment by argosopentech** [comment]
https://github.com/argosopentech/argos-translate-gui/commit/7a7149887f3e2206c5737b49b7c9a25e492caab7
